services:
  postgres:
    image: "postgres:15"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: local-dev123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  redis:
    image: "redis:alpine"
    ports: 
      - "6379:6379"

