name: Deploy to Fly.io dev bot

# todo split this into two in the future
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  deploy:
    name: Deploy dev bot
    runs-on: ubuntu-latest
    environment: dev
    concurrency: dev-deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -a birthday-bot-dev-rr --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

